import { createContext, useContext, useState, useEffect } from 'react';

const STORAGE_KEY = 'vida_language';

// Translations
const translations = {
  'pt-BR': {
    // Common
    app_name: 'Vida',
    app_tagline: 'Estrutura real. Vida real.',
    continue: 'Continuar',
    back: 'Voltar',
    save: 'Salvar',
    cancel: 'Cancelar',
    loading: 'Carregando...',
    logout: 'Sair',
    skip: 'Pular',

    // Navigation
    nav_schedule: 'Semana',
    nav_meals: 'Refeições',
    nav_training: 'Treino',
    nav_progress: 'Progresso',

    // Onboarding - Welcome
    onboarding_welcome_title: 'Bem-vindo ao Vida',
    onboarding_welcome_desc: 'Vamos criar uma rotina personalizada pra você. Em poucos passos, você terá um plano de treino, alimentação e horários adaptados ao seu estilo de vida.',
    onboarding_start: 'Começar',
    onboarding_step: 'Passo',
    onboarding_of: 'de',

    // Onboarding Step 1 - Wake Time
    step_wake_title: 'A que horas você costuma acordar?',
    step_wake_desc: 'Vamos usar isso pra calcular sua rotina ideal',
    step_wake_label: 'Hora de acordar',
    step_wake_late_warning_title: 'Rotina diferente detectada',
    step_wake_late_warning_desc: 'Acordar depois das 10h pode dificultar alguns horários tradicionais. Vamos adaptar sua rotina pra funcionar com seu estilo.',

    // Onboarding Step 2 - Sleep Hours
    step_sleep_title: 'Quantas horas você dorme por noite?',
    step_sleep_desc: 'O sono é essencial pra recuperação e resultados',
    step_sleep_label: 'Horas de sono',
    step_sleep_feedback_low: 'Hmm, pode estar dormindo pouco. O ideal é 7-8h.',
    step_sleep_feedback_good: 'Perfeito! Essa é uma quantidade saudável.',
    step_sleep_feedback_high: 'Ótimo! Sono de sobra pra recuperar.',

    // Onboarding Step 3 - Lunch Time
    step_lunch_title: 'A que horas você costuma almoçar?',
    step_lunch_desc: 'Isso nos ajuda a organizar suas refeições e atividades',
    step_lunch_label: 'Hora do almoço',

    // Onboarding Step 4 - Dinner Time
    step_dinner_title: 'A que horas você costuma jantar?',
    step_dinner_desc: 'O ideal é ter pelo menos 3h entre almoço e jantar',
    step_dinner_label: 'Hora do jantar',
    step_dinner_gap_warning: 'Atenção: menos de 3h entre almoço e jantar. Considere ajustar.',

    // Onboarding Step 5 - Gym Preference
    step_gym_title: 'Quando você prefere treinar?',
    step_gym_desc: 'Escolha o horário que funciona melhor pra você',
    step_gym_morning: 'De manhã',
    step_gym_morning_desc: 'Antes de começar o dia',
    step_gym_evening: 'De noite',
    step_gym_evening_desc: 'Depois do trabalho',
    step_gym_flexible: 'Flexível',
    step_gym_flexible_desc: 'Depende do dia',

    // Onboarding Step 6 - Office Days
    step_office_title: 'Quantos dias você vai ao escritório?',
    step_office_desc: 'Isso nos ajuda a organizar seus dias de forma diferente',
    step_office_count_label: 'Dias por semana',
    step_office_times_label: 'Horário de trabalho',
    step_office_start: 'Entrada',
    step_office_end: 'Saída',
    step_office_remote: 'Trabalho 100% remoto',

    // Onboarding Step 7 - Goals
    step_goals_title: 'Quais são seus objetivos?',
    step_goals_desc: 'Selecione todos que se aplicam',
    step_goals_muscle: 'Ganhar massa muscular',
    step_goals_fat_loss: 'Perder gordura',
    step_goals_health: 'Melhorar a saúde',
    step_goals_energy: 'Ter mais energia',
    step_goals_strength: 'Ficar mais forte',
    step_goals_flexibility: 'Melhorar flexibilidade',
    step_goals_endurance: 'Mais resistência',
    step_goals_sleep: 'Dormir melhor',

    // Onboarding Step 8 - Physical Data
    step_physical_title: 'Seus dados físicos',
    step_physical_desc: 'Opcional, mas ajuda a personalizar ainda mais',
    step_physical_sex: 'Sexo biológico',
    step_physical_male: 'Masculino',
    step_physical_female: 'Feminino',
    step_physical_age: 'Idade',
    step_physical_weight: 'Peso (kg)',
    step_physical_height: 'Altura (cm)',
    step_physical_bodyfat: 'Gordura corporal (%)',
    step_physical_recomp_title: 'Recomposição corporal',
    step_physical_recomp_desc: 'Acompanhar medidas detalhadas',
    step_physical_skip_hint: 'Você pode pular e adicionar depois',

    // Profile step (kept for compatibility)
    profile_title: 'Seu perfil',
    profile_desc: 'Informações básicas pra personalizar sua experiência',
    profile_name: 'Nome',
    profile_name_placeholder: 'Como você se chama?',
    profile_sex: 'Sexo',
    profile_sex_male: 'Masculino',
    profile_sex_female: 'Feminino',
    profile_age: 'Idade',
    profile_age_placeholder: 'Ex: 28',
    profile_current_weight: 'Peso atual (kg)',
    profile_target_weight: 'Peso alvo (kg)',
    profile_height: 'Altura (cm)',
    optional: '(opcional)',
    required: '*',

    // Routine step
    routine_title: 'Sua rotina',
    routine_desc: 'Como é o seu dia a dia?',
    routine_wake_up: 'Você acorda às',
    routine_sleep: 'Você dorme às',
    routine_dinner: 'Você janta às',
    routine_office_days: 'Dias de escritório',
    routine_office_hint: 'Selecione os dias que você vai ao escritório',
    routine_work_from_home: 'Trabalha sempre de casa? Deixe em branco.',
    routine_days_selected: 'dia(s) selecionado(s)',

    // Lifestyle step
    lifestyle_title: 'Estilo de vida',
    lifestyle_desc: 'Pra criar uma rotina que funciona pra você',
    lifestyle_hobbies: 'Você tem hobbies regulares?',
    lifestyle_hobbies_hint: 'Ex: jogos, música, esportes, leitura...',
    lifestyle_chores: 'Com que frequência você faz tarefas de casa?',
    lifestyle_chores_daily: 'Diariamente',
    lifestyle_chores_weekly: 'Semanalmente',
    lifestyle_chores_rarely: 'Raramente',
    lifestyle_grocery: 'Frequência de compras no mercado',
    lifestyle_grocery_weekly: 'Semanal',
    lifestyle_grocery_biweekly: 'Quinzenal',
    lifestyle_grocery_monthly: 'Mensal',
    lifestyle_weekend: 'Como é seu final de semana?',
    lifestyle_weekend_relaxed: 'Relaxado',
    lifestyle_weekend_relaxed_desc: 'Acordo tarde, sem horário fixo',
    lifestyle_weekend_active: 'Ativo',
    lifestyle_weekend_active_desc: 'Mantenho a rotina, faço atividades',

    // Training step
    training_title: 'Seu treino',
    training_desc: 'Personalize seu plano de treino',
    training_goal: 'Qual é seu objetivo principal?',
    training_goal_muscle: 'Ganhar massa',
    training_goal_muscle_desc: 'Hipertrofia muscular',
    training_goal_loss: 'Perder peso',
    training_goal_loss_desc: 'Queimar gordura',
    training_goal_maintain: 'Manter forma',
    training_goal_maintain_desc: 'Estabilidade',
    training_goal_general: 'Fitness geral',
    training_goal_general_desc: 'Saúde e bem-estar',
    training_level: 'Nível de experiência',
    training_level_beginner: 'Iniciante',
    training_level_beginner_desc: 'Menos de 1 ano de treino',
    training_level_intermediate: 'Intermediário',
    training_level_intermediate_desc: '1-3 anos de treino',
    training_level_advanced: 'Avançado',
    training_level_advanced_desc: 'Mais de 3 anos de treino',
    training_days: 'Dias de treino por semana',
    training_days_hint: 'Selecione os dias que você vai treinar',
    training_time: 'Horário preferido de treino',
    training_time_morning: 'Manhã',
    training_time_afternoon: 'Tarde',
    training_time_evening: 'Noite',

    // Nutrition step
    nutrition_title: 'Alimentação',
    nutrition_desc: 'Últimos detalhes pro seu plano alimentar',
    nutrition_restrictions: 'Restrições alimentares',
    nutrition_vegetarian: 'Vegetariano',
    nutrition_vegan: 'Vegano',
    nutrition_lactose_free: 'Sem lactose',
    nutrition_gluten_free: 'Sem glúten',
    nutrition_meal_prep: 'Você prepara refeições com antecedência?',
    nutrition_meal_prep_yes: 'Sim, faço meal prep',
    nutrition_meal_prep_yes_desc: 'Preparo refeições pra vários dias',
    nutrition_meal_prep_no: 'Não, cozinho no dia',
    nutrition_meal_prep_no_desc: 'Preparo cada refeição na hora',

    // Language step
    language_title: 'Idioma',
    language_desc: 'Em qual idioma você prefere usar o app?',
    language_pt: 'Português (Brasil)',
    language_en: 'English',

    // Summary
    summary_title: 'Resumo do seu plano',
    summary_goal: 'Objetivo',
    summary_training: 'Treino',
    summary_time: 'Horário',
    summary_weight: 'Meta',
    summary_per_week: 'x por semana',
    create_routine: 'Criar minha rotina',

    // Generating
    generating_title: 'Criando sua rotina...',
    generating_desc: 'Estamos personalizando seus horários com base na sua rotina.',
    generating_step_1: 'Analisando rotina',
    generating_step_2: 'Calculando horários',
    generating_step_3: 'Montando cronograma',
    generating_step_4: 'Finalizando',

    // Exercise type step
    exercise_type_title: 'Tipo de exercício',
    exercise_type_desc: 'Que tipo de atividade física você pratica?',
    exercise_type_gym: 'Academia',
    exercise_type_gym_desc: 'Musculação, cardio, funcional...',
    exercise_type_sports: 'Esportes',
    exercise_type_sports_desc: 'Futebol, natação, corrida...',
    exercise_type_both: 'Ambos',
    exercise_type_both_desc: 'Academia + esportes',
    exercise_type_none: 'Nenhum',
    exercise_type_none_desc: 'Vou começar agora',

    // Gym details step
    gym_details_title: 'Detalhes da academia',
    gym_details_desc: 'Personalize seu plano de treino',
    gym_type_question: 'Que tipo de treino você faz?',
    gym_type_hint: 'Selecione um ou mais tipos',

    // Sports details step
    sports_details_title: 'Seus esportes',
    sports_details_desc: 'Quais esportes você pratica?',
    sports_select: 'Selecione seus esportes',
    sports_schedule: 'Horários de cada esporte',
    sports_which_days: 'Quais dias?',
    sports_what_time: 'Que horário?',

    // Summary additions
    summary_sports: 'Esportes',
    summary_sport: 'esporte',
    summary_sports_plural: 'esportes',

    // Errors
    error_required_sex: 'Selecione seu sexo',
    error_required_age: 'Informe sua idade',
    error_required_weight: 'Informe seu peso atual',
    error_required_target: 'Informe seu peso alvo',
    error_required_goal: 'Selecione seu objetivo',
    error_required_level: 'Selecione seu nível',
    error_required_days: 'Selecione pelo menos um dia',
    error_required_time: 'Selecione o horário preferido',
    error_required_meal_prep: 'Selecione uma opção',
    error_required_weekend: 'Selecione como é seu fim de semana',
    error_required_exercise_type: 'Selecione o tipo de exercício',
    error_required_gym_type: 'Selecione pelo menos um tipo de treino',
    error_required_sports: 'Selecione pelo menos um esporte',
    error_required_sports_schedule: 'Defina os dias para cada esporte',
    error_required_goals: 'Selecione pelo menos um objetivo',
    error_required_gym_pref: 'Selecione seu horário preferido',

    // Settings
    settings_title: 'Configurações',
    settings_profile: 'Editar perfil',
    settings_redo_onboarding: 'Refazer questionário',
    settings_language: 'Idioma',
    settings_my_activities: 'Minhas Atividades',
    settings_add_activity: 'Adicionar Atividade',
    settings_main_activity: 'Principal',
    settings_addon_activity: 'Opcional',
    settings_per_week: '/sem',
    settings_already_added: 'Já adicionado',
    settings_remove: 'Remover',
    settings_remove_confirm: 'Remover {activity}? Seu plano será atualizado.',
    settings_plan_updated: 'Plano atualizado!',
    settings_max_days_warning: 'Máximo de 7 dias por semana',
    settings_min_main_warning: 'Você precisa de pelo menos uma atividade principal',

    // Progress Page - Enhanced
    progress_mode_basic: 'Básico',
    progress_mode_advanced: 'Avançado',
    progress_add_entry: 'Registrar Dados',
    progress_body_fat: 'Gordura Corporal',
    progress_measurements: 'Medidas',
    progress_arm: 'Braço',
    progress_waist: 'Cintura',
    progress_chest: 'Peito',
    progress_thigh: 'Coxa',
    progress_cm: 'cm',
    progress_percent: '%',
    progress_last_entry: 'Último registro',
    progress_no_previous: 'Primeiro registro',
    progress_recomp_title: 'O que é recomposição corporal?',
    progress_recomp_desc: 'Recomposição é perder gordura e ganhar músculo ao mesmo tempo. O peso na balança pode não mudar muito, mas seu corpo está se transformando. Acompanhe suas medidas e % de gordura para ver o progresso real.',
    progress_motivational_1: 'Continue assim! Consistência é a chave.',
    progress_motivational_2: 'Cada registro te aproxima do objetivo.',
    progress_motivational_3: 'Você está construindo um novo você!',
    progress_motivational_4: 'Progresso não é linear, mas é real.',
    progress_motivational_5: 'Confiança no processo!',
    progress_weight_chart: 'Evolução do Peso',
    progress_bodyfat_chart: 'Evolução da Gordura',
    progress_no_bodyfat_data: 'Registre sua gordura corporal para ver o gráfico',

    // Dashboard
    nav_dashboard: 'Dashboard',
    dashboard_greeting: 'Olá',
    dashboard_rest_day: 'Dia de Descanso',
    dashboard_rest_message: 'Aproveite o descanso, amanhã tem mais!',
    dashboard_start: 'Iniciar',
    dashboard_sessions_week: 'esta semana',
    dashboard_volume: 'volume',
    dashboard_prs_month: 'PRs este mês',
    dashboard_distance: 'distância',
    dashboard_sessions_month: 'este mês',
    dashboard_longest_streak: 'maior sequência',
    dashboard_skills_up: 'skills up',
    dashboard_rounds: 'rounds',
    dashboard_week_streak: 'semanas',
    dashboard_monthly_report: 'Relatório Mensal',
    dashboard_workouts: 'Treinos',
    dashboard_duration: 'Duração',
    dashboard_sets: 'Séries',
    dashboard_muscle_distribution: 'Distribuição Muscular',
    dashboard_last_7_days: 'Últimos 7 dias',
    dashboard_last_30_days: 'Últimos 30 dias',
    dashboard_last_90_days: 'Últimos 90 dias',
    dashboard_current: 'Atual',
    dashboard_previous: 'Anterior',
    dashboard_progression: 'Progressão',
    dashboard_search_exercise: 'Buscar exercício...',
    dashboard_recent: 'Recentes',
    dashboard_heaviest: 'Maior Peso',
    dashboard_one_rm: '1RM',
    dashboard_best_score: 'Melhor Score',
    dashboard_average: 'Média',
    dashboard_pace: 'Pace',
    dashboard_last: 'Último',
    dashboard_best: 'Melhor',
    dashboard_body: 'Corpo',
    dashboard_body_fat: 'Gordura Corporal',
    dashboard_weight: 'Peso',
    dashboard_to_goal: 'até a meta',
    dashboard_log_measurement: 'Registrar Medida',
    dashboard_3m: '3M',
    dashboard_6m: '6M',
    dashboard_1y: '1A',
    dashboard_empty_calendar: 'Complete um treino para ver seu histórico aqui.',
    dashboard_empty_progression: 'Busque um exercício para ver sua progressão.',
    dashboard_exercises: 'exercícios',
    dashboard_movements: 'movimentos',
    dashboard_progressions: 'progressões',
    dashboard_poses: 'poses',
    dashboard_min_cap: 'min cap',
    dashboard_tomorrow: 'Amanhã',

    // Activity selection (onboarding)
    onboarding_activity_title: 'Como você treina?',
    onboarding_activity_subtitle: 'Selecione todas que pratica',
    activity_gym: 'Academia',
    activity_crossfit: 'CrossFit',
    activity_calisthenics: 'Calistenia',
    activity_pilates: 'Pilates',

    // Activity add-ons (onboarding)
    onboarding_addons_title: 'Pratica mais alguma?',
    onboarding_addons_skip: 'Pular',
    activity_running: 'Corrida',
    activity_yoga: 'Yoga',
    frequency_label: 'vezes/semana',

    // Activity time preference (onboarding)
    onboarding_time_title: 'Quando prefere treinar?',
    time_morning: 'Manhã',
    time_afternoon: 'Tarde',
    time_evening: 'Noite',
    time_flexible: 'Flexível',

    // Activity card labels
    crossfit_wod: 'WOD',
    crossfit_rounds: 'Rounds',
    crossfit_score: 'Score',
    crossfit_movements: 'Movimentos',
    calisthenics_level: 'Nível',
    calisthenics_hold: 'Segurar',
    calisthenics_sets: 'Séries',
    pilates_flow: 'Flow',
    pilates_duration: 'Duração',
    pilates_moves: 'Movimentos',
    running_distance: 'Distância',
    running_pace: 'Pace',
    running_zone: 'Zona',
    yoga_style: 'Estilo',
    yoga_duration: 'Duração',
    yoga_focus: 'Foco',

    // Exercise Library
    nav_library: 'Exercícios',
    nav_programs: 'Programas',
    library_title: 'Biblioteca de Exercícios',
    library_search_placeholder: 'Buscar exercícios...',
    library_filter_chest: 'Peito',
    library_filter_back: 'Costas',
    library_filter_shoulders: 'Ombros',
    library_filter_arms: 'Braços',
    library_filter_legs: 'Pernas',
    library_filter_core: 'Core',
    library_filter_fullbody: 'Todos',
    library_filter_barbell: 'Barra',
    library_filter_dumbbell: 'Haltere',
    library_filter_cable: 'Cabo',
    library_filter_machine: 'Máquina',
    library_filter_bodyweight: 'Corpo',
    library_filter_band: 'Elástico',
    library_empty_filter: 'Nenhum exercício com esses filtros. Tente remover um filtro.',
    library_empty_search: 'Nenhum exercício encontrado para',
    library_offline_footer: 'Mostrando biblioteca offline',
    library_staleness: 'Atualizado há',
    library_staleness_days: 'dias',
    library_refresh: 'Atualizar',
    library_detail_instructions: 'Instruções',
    library_detail_similar: 'Exercícios similares',
    library_detail_level: 'Nível',
    library_detail_equipment: 'Equipamento',
    library_detail_muscles: 'Músculos',

    // Library Filters (redesign)
    library_filters_button: 'Filtros',
    library_filters_clear: 'Limpar',
    library_filters_clear_all: 'Limpar tudo',
    library_filters_show_results: 'Ver resultados',
    library_filters_muscle_group: 'Grupo Muscular',
    library_filters_equipment: 'Equipamento',
    library_filters_level: 'Nível',
    library_filter_beginner: 'Iniciante',
    library_filter_intermediate: 'Intermediário',
    library_filter_expert: 'Avançado',

    // Training Page - Plan Selection
    training_empty_title: 'Seu treino começa aqui',
    training_empty_desc: 'Escolha como montar seu plano de treino',
    training_option_smart: 'Plano Inteligente',
    training_option_smart_desc: 'Respondemos algumas perguntas e montamos pra você',
    training_option_scratch: 'Montar do Zero',
    training_option_scratch_desc: 'Monte seu próprio plano personalizado',
    training_option_programs: 'Explorar Programas',
    training_option_programs_desc: 'Escolha entre programas prontos e testados',
    training_active_plan: 'Plano Ativo',
    training_change_plan: 'Trocar plano',

    // Programs Page
    programs_title: 'Programas',
    programs_for_you: 'Para Você',
    programs_all: 'Todos',
    programs_weeks: 'semanas',
    programs_days_week: 'dias/sem',
    programs_start: 'Começar Programa',
    programs_back: 'Voltar',
    programs_empty: 'Nenhum programa encontrado com esses filtros.',
    programs_modality_gym: 'Academia',
    programs_modality_crossfit: 'CrossFit',
    programs_modality_calisthenics: 'Calistenia',
    programs_modality_pilates: 'Pilates',
    programs_modality_running: 'Corrida',
    programs_modality_yoga: 'Yoga',
    programs_modality_mixed: 'Misto',
    programs_level_beginner: 'Iniciante',
    programs_level_intermediate: 'Intermediário',
    programs_level_advanced: 'Avançado',
    programs_goal_muscle: 'Hipertrofia',
    programs_goal_fat_loss: 'Queima',
    programs_goal_strength: 'Força',
    programs_goal_endurance: 'Resistência',
    programs_goal_flexibility: 'Flexibilidade',
    programs_goal_general: 'Geral',
    programs_duration: 'Duração',
    programs_frequency: 'Frequência',
    programs_level: 'Nível',
    programs_goal: 'Objetivo',
    programs_about: 'Sobre',
    programs_day: 'Dia',
    programs_smart_title: 'Treinador Inteligente',
    programs_smart_desc: 'Responda algumas perguntas e receba um plano personalizado',

    // Workout Builder
    builder_title: 'Montar Treino',
    builder_name_placeholder: 'Nome do treino (ex: Meu Treino A)',
    builder_select_days: 'Dias da semana',
    builder_mon: 'Seg',
    builder_tue: 'Ter',
    builder_wed: 'Qua',
    builder_thu: 'Qui',
    builder_fri: 'Sex',
    builder_sat: 'Sáb',
    builder_sun: 'Dom',
    builder_empty: 'Toque em + para adicionar exercícios',
    builder_add_exercise: 'Adicionar exercício',
    builder_sets: 'Séries',
    builder_reps: 'Reps',
    builder_deleted: 'Exercício removido',
    builder_undo: 'Desfazer',
    builder_days_label: 'dias',
    builder_exercises_label: 'exercícios',
    builder_save: 'Salvar Treino',
    builder_pick_exercise: 'Escolher Exercício',
    builder_search_placeholder: 'Buscar exercício...',
    builder_no_results: 'Nenhum exercício encontrado',

    // Smart Plan Questionnaire
    smart_plan_title: 'Plano Inteligente',
    smart_step: 'Passo',
    smart_of: 'de',
    smart_next: 'Próximo',
    smart_finish: 'Ver meu plano',
    smart_q1_title: 'Quais são seus objetivos?',
    smart_q1_desc: 'Selecione até 3 objetivos',
    smart_q1_muscle: 'Ganhar massa muscular',
    smart_q1_fat_loss: 'Perder gordura',
    smart_q1_strength: 'Ficar mais forte',
    smart_q1_endurance: 'Mais resistência',
    smart_q1_general: 'Saúde geral',
    smart_q2_title: 'Qual seu nível de experiência?',
    smart_q2_beginner: 'Iniciante',
    smart_q2_beginner_desc: 'Menos de 1 ano treinando',
    smart_q2_intermediate: 'Intermediário',
    smart_q2_intermediate_desc: '1-3 anos treinando',
    smart_q2_advanced: 'Avançado',
    smart_q2_advanced_desc: 'Mais de 3 anos treinando',
    smart_q3_title: 'Quantos dias por semana?',
    smart_q3_desc: 'Recomendamos pelo menos 3 dias para bons resultados',
    smart_q4_title: 'Onde você vai treinar?',
    smart_q4_full_gym: 'Academia completa',
    smart_q4_full_gym_desc: 'Barras, máquinas, cabos, halteres',
    smart_q4_home: 'Em casa',
    smart_q4_home_desc: 'Halteres e peso corporal',
    smart_q4_minimal: 'Equipamento mínimo',
    smart_q4_minimal_desc: 'Apenas peso corporal',
    smart_q5_title: 'Quanto tempo por sessão?',
    smart_q5_30: '30 min',
    smart_q5_45: '45 min',
    smart_q5_60: '60 min',
    smart_q5_90: '90 min',
    smart_result_title: 'Seu Plano Está Pronto!',
    smart_result_desc: 'Criamos um plano personalizado baseado nas suas respostas.',
    smart_result_goal: 'Objetivo',
    smart_result_level: 'Nível',
    smart_result_days: 'Dias/semana',
    smart_result_duration: 'Duração/sessão',
    smart_result_equipment: 'Local',
    smart_result_activate: 'Ativar Plano',
    smart_result_back: 'Voltar e ajustar',
    smart_result_exercises: 'Exercícios',
    smart_result_priority: 'Músculos Prioritários',
    smart_result_progression: 'Modelo de Progressão',

    // Plan Preview
    smart_preview_title: 'Seu Plano de Treino',
    smart_preview_hint: 'Toque no ícone de troca para substituir um exercício ou no X para removê-lo',
    smart_preview_swap: 'Trocar exercício',
    smart_preview_remove: 'Remover exercício',
    smart_preview_empty: 'Nenhum exercício neste dia',

    // Step 6: Priority Muscles
    smart_q6_title: 'Foco especial em algum músculo?',
    smart_q6_desc: 'Selecione até 2 músculos para priorizar. Opcional — pule se quiser treino equilibrado.',
    smart_q6_skip: 'Nenhum selecionado — treino equilibrado para todos os grupos.',

    // Muscle names
    muscle_chest: 'Peito',
    muscle_back: 'Costas',
    muscle_shoulders: 'Ombros',
    muscle_quads: 'Quadríceps',
    muscle_hamstrings: 'Posterior',
    muscle_glutes: 'Glúteos',
    muscle_biceps: 'Bíceps',
    muscle_triceps: 'Tríceps',
    muscle_calves: 'Panturrilhas',
    muscle_abs: 'Abdômen',
  },

  'en': {
    // Common
    app_name: 'Vida',
    app_tagline: 'Real structure. Real life.',
    continue: 'Continue',
    back: 'Back',
    save: 'Save',
    cancel: 'Cancel',
    loading: 'Loading...',
    logout: 'Log out',
    skip: 'Skip',

    // Navigation
    nav_schedule: 'Week',
    nav_meals: 'Meals',
    nav_training: 'Training',
    nav_progress: 'Progress',

    // Onboarding - Welcome
    onboarding_welcome_title: 'Welcome to Vida',
    onboarding_welcome_desc: "Let's create a personalized routine for you. In a few steps, you'll have a training plan, nutrition, and schedule adapted to your lifestyle.",
    onboarding_start: 'Get Started',
    onboarding_step: 'Step',
    onboarding_of: 'of',

    // Onboarding Step 1 - Wake Time
    step_wake_title: 'What time do you usually wake up?',
    step_wake_desc: "We'll use this to calculate your ideal routine",
    step_wake_label: 'Wake up time',
    step_wake_late_warning_title: 'Different routine detected',
    step_wake_late_warning_desc: "Waking up after 10am may make some traditional schedules harder. We'll adapt your routine to fit your style.",

    // Onboarding Step 2 - Sleep Hours
    step_sleep_title: 'How many hours do you sleep per night?',
    step_sleep_desc: 'Sleep is essential for recovery and results',
    step_sleep_label: 'Hours of sleep',
    step_sleep_feedback_low: 'Hmm, you might be sleeping too little. Ideal is 7-8h.',
    step_sleep_feedback_good: 'Perfect! That is a healthy amount.',
    step_sleep_feedback_high: 'Great! Plenty of sleep to recover.',

    // Onboarding Step 3 - Lunch Time
    step_lunch_title: 'What time do you usually have lunch?',
    step_lunch_desc: 'This helps us organize your meals and activities',
    step_lunch_label: 'Lunch time',

    // Onboarding Step 4 - Dinner Time
    step_dinner_title: 'What time do you usually have dinner?',
    step_dinner_desc: 'Ideally at least 3h between lunch and dinner',
    step_dinner_label: 'Dinner time',
    step_dinner_gap_warning: 'Note: less than 3h between lunch and dinner. Consider adjusting.',

    // Onboarding Step 5 - Gym Preference
    step_gym_title: 'When do you prefer to workout?',
    step_gym_desc: 'Choose the time that works best for you',
    step_gym_morning: 'Morning',
    step_gym_morning_desc: 'Before starting the day',
    step_gym_evening: 'Evening',
    step_gym_evening_desc: 'After work',
    step_gym_flexible: 'Flexible',
    step_gym_flexible_desc: 'Depends on the day',

    // Onboarding Step 6 - Office Days
    step_office_title: 'How many days do you go to the office?',
    step_office_desc: 'This helps us organize your days differently',
    step_office_count_label: 'Days per week',
    step_office_times_label: 'Work hours',
    step_office_start: 'Start',
    step_office_end: 'End',
    step_office_remote: '100% remote work',

    // Onboarding Step 7 - Goals
    step_goals_title: 'What are your goals?',
    step_goals_desc: 'Select all that apply',
    step_goals_muscle: 'Build muscle',
    step_goals_fat_loss: 'Lose fat',
    step_goals_health: 'Improve health',
    step_goals_energy: 'Have more energy',
    step_goals_strength: 'Get stronger',
    step_goals_flexibility: 'Improve flexibility',
    step_goals_endurance: 'More endurance',
    step_goals_sleep: 'Sleep better',

    // Onboarding Step 8 - Physical Data
    step_physical_title: 'Your physical data',
    step_physical_desc: 'Optional, but helps personalize even more',
    step_physical_sex: 'Biological sex',
    step_physical_male: 'Male',
    step_physical_female: 'Female',
    step_physical_age: 'Age',
    step_physical_weight: 'Weight (kg)',
    step_physical_height: 'Height (cm)',
    step_physical_bodyfat: 'Body fat (%)',
    step_physical_recomp_title: 'Body recomposition',
    step_physical_recomp_desc: 'Track detailed measurements',
    step_physical_skip_hint: 'You can skip and add later',

    // Profile step (kept for compatibility)
    profile_title: 'Your profile',
    profile_desc: 'Basic information to personalize your experience',
    profile_name: 'Name',
    profile_name_placeholder: "What's your name?",
    profile_sex: 'Sex',
    profile_sex_male: 'Male',
    profile_sex_female: 'Female',
    profile_age: 'Age',
    profile_age_placeholder: 'Ex: 28',
    profile_current_weight: 'Current weight (kg)',
    profile_target_weight: 'Target weight (kg)',
    profile_height: 'Height (cm)',
    optional: '(optional)',
    required: '*',

    // Routine step
    routine_title: 'Your routine',
    routine_desc: "What's your daily life like?",
    routine_wake_up: 'You wake up at',
    routine_sleep: 'You sleep at',
    routine_dinner: 'You have dinner at',
    routine_office_days: 'Office days',
    routine_office_hint: 'Select the days you go to the office',
    routine_work_from_home: 'Always work from home? Leave blank.',
    routine_days_selected: 'day(s) selected',

    // Lifestyle step
    lifestyle_title: 'Lifestyle',
    lifestyle_desc: 'To create a routine that works for you',
    lifestyle_hobbies: 'Do you have regular hobbies?',
    lifestyle_hobbies_hint: 'Ex: gaming, music, sports, reading...',
    lifestyle_chores: 'How often do you do house chores?',
    lifestyle_chores_daily: 'Daily',
    lifestyle_chores_weekly: 'Weekly',
    lifestyle_chores_rarely: 'Rarely',
    lifestyle_grocery: 'Grocery shopping frequency',
    lifestyle_grocery_weekly: 'Weekly',
    lifestyle_grocery_biweekly: 'Bi-weekly',
    lifestyle_grocery_monthly: 'Monthly',
    lifestyle_weekend: 'How are your weekends?',
    lifestyle_weekend_relaxed: 'Relaxed',
    lifestyle_weekend_relaxed_desc: 'Wake up late, no fixed schedule',
    lifestyle_weekend_active: 'Active',
    lifestyle_weekend_active_desc: 'Keep the routine, do activities',

    // Training step
    training_title: 'Your training',
    training_desc: 'Customize your training plan',
    training_goal: "What's your main goal?",
    training_goal_muscle: 'Build muscle',
    training_goal_muscle_desc: 'Muscle hypertrophy',
    training_goal_loss: 'Lose weight',
    training_goal_loss_desc: 'Burn fat',
    training_goal_maintain: 'Maintain',
    training_goal_maintain_desc: 'Stay stable',
    training_goal_general: 'General fitness',
    training_goal_general_desc: 'Health and wellness',
    training_level: 'Experience level',
    training_level_beginner: 'Beginner',
    training_level_beginner_desc: 'Less than 1 year training',
    training_level_intermediate: 'Intermediate',
    training_level_intermediate_desc: '1-3 years training',
    training_level_advanced: 'Advanced',
    training_level_advanced_desc: 'More than 3 years training',
    training_days: 'Training days per week',
    training_days_hint: 'Select the days you will train',
    training_time: 'Preferred training time',
    training_time_morning: 'Morning',
    training_time_afternoon: 'Afternoon',
    training_time_evening: 'Evening',

    // Nutrition step
    nutrition_title: 'Nutrition',
    nutrition_desc: 'Last details for your meal plan',
    nutrition_restrictions: 'Dietary restrictions',
    nutrition_vegetarian: 'Vegetarian',
    nutrition_vegan: 'Vegan',
    nutrition_lactose_free: 'Lactose-free',
    nutrition_gluten_free: 'Gluten-free',
    nutrition_meal_prep: 'Do you meal prep?',
    nutrition_meal_prep_yes: 'Yes, I meal prep',
    nutrition_meal_prep_yes_desc: 'I prepare meals for several days',
    nutrition_meal_prep_no: 'No, I cook daily',
    nutrition_meal_prep_no_desc: 'I prepare each meal fresh',

    // Language step
    language_title: 'Language',
    language_desc: 'Which language do you prefer?',
    language_pt: 'Português (Brasil)',
    language_en: 'English',

    // Summary
    summary_title: 'Your plan summary',
    summary_goal: 'Goal',
    summary_training: 'Training',
    summary_time: 'Time',
    summary_weight: 'Target',
    summary_per_week: 'x per week',
    create_routine: 'Create my routine',

    // Generating
    generating_title: 'Creating your routine...',
    generating_desc: "We're personalizing your schedule based on your routine.",
    generating_step_1: 'Analyzing routine',
    generating_step_2: 'Calculating times',
    generating_step_3: 'Building schedule',
    generating_step_4: 'Finishing up',

    // Exercise type step
    exercise_type_title: 'Exercise type',
    exercise_type_desc: 'What type of physical activity do you do?',
    exercise_type_gym: 'Gym',
    exercise_type_gym_desc: 'Weight training, cardio, functional...',
    exercise_type_sports: 'Sports',
    exercise_type_sports_desc: 'Soccer, swimming, running...',
    exercise_type_both: 'Both',
    exercise_type_both_desc: 'Gym + sports',
    exercise_type_none: 'None',
    exercise_type_none_desc: "I'm starting now",

    // Gym details step
    gym_details_title: 'Gym details',
    gym_details_desc: 'Customize your training plan',
    gym_type_question: 'What type of training do you do?',
    gym_type_hint: 'Select one or more types',

    // Sports details step
    sports_details_title: 'Your sports',
    sports_details_desc: 'Which sports do you practice?',
    sports_select: 'Select your sports',
    sports_schedule: 'Schedule for each sport',
    sports_which_days: 'Which days?',
    sports_what_time: 'What time?',

    // Summary additions
    summary_sports: 'Sports',
    summary_sport: 'sport',
    summary_sports_plural: 'sports',

    // Errors
    error_required_sex: 'Select your sex',
    error_required_age: 'Enter your age',
    error_required_weight: 'Enter your current weight',
    error_required_target: 'Enter your target weight',
    error_required_goal: 'Select your goal',
    error_required_level: 'Select your level',
    error_required_days: 'Select at least one day',
    error_required_time: 'Select your preferred time',
    error_required_meal_prep: 'Select an option',
    error_required_weekend: 'Select your weekend style',
    error_required_exercise_type: 'Select the exercise type',
    error_required_gym_type: 'Select at least one training type',
    error_required_sports: 'Select at least one sport',
    error_required_sports_schedule: 'Set the days for each sport',
    error_required_goals: 'Select at least one goal',
    error_required_gym_pref: 'Select your preferred time',

    // Settings
    settings_title: 'Settings',
    settings_profile: 'Edit profile',
    settings_redo_onboarding: 'Redo questionnaire',
    settings_language: 'Language',
    settings_my_activities: 'My Activities',
    settings_add_activity: 'Add Activity',
    settings_main_activity: 'Main',
    settings_addon_activity: 'Optional',
    settings_per_week: '/week',
    settings_already_added: 'Already added',
    settings_remove: 'Remove',
    settings_remove_confirm: 'Remove {activity}? Your plan will be updated.',
    settings_plan_updated: 'Plan updated!',
    settings_max_days_warning: 'Maximum 7 days per week',
    settings_min_main_warning: 'You need at least one main activity',

    // Progress Page - Enhanced
    progress_mode_basic: 'Basic',
    progress_mode_advanced: 'Advanced',
    progress_add_entry: 'Log Data',
    progress_body_fat: 'Body Fat',
    progress_measurements: 'Measurements',
    progress_arm: 'Arm',
    progress_waist: 'Waist',
    progress_chest: 'Chest',
    progress_thigh: 'Thigh',
    progress_cm: 'cm',
    progress_percent: '%',
    progress_last_entry: 'Last entry',
    progress_no_previous: 'First entry',
    progress_recomp_title: 'What is body recomposition?',
    progress_recomp_desc: 'Recomposition is losing fat and building muscle at the same time. The scale might not change much, but your body is transforming. Track your measurements and body fat % to see real progress.',
    progress_motivational_1: 'Keep it up! Consistency is key.',
    progress_motivational_2: 'Each entry brings you closer to your goal.',
    progress_motivational_3: "You're building a new you!",
    progress_motivational_4: "Progress isn't linear, but it's real.",
    progress_motivational_5: 'Trust the process!',
    progress_weight_chart: 'Weight History',
    progress_bodyfat_chart: 'Body Fat History',
    progress_no_bodyfat_data: 'Log your body fat to see the chart',

    // Dashboard
    nav_dashboard: 'Dashboard',
    dashboard_greeting: 'Hi',
    dashboard_rest_day: 'Rest Day',
    dashboard_rest_message: 'Enjoy the rest, tomorrow we go again!',
    dashboard_start: 'Start',
    dashboard_sessions_week: 'this week',
    dashboard_volume: 'volume',
    dashboard_prs_month: 'PRs this month',
    dashboard_distance: 'distance',
    dashboard_sessions_month: 'this month',
    dashboard_longest_streak: 'longest streak',
    dashboard_skills_up: 'skills up',
    dashboard_rounds: 'rounds',
    dashboard_week_streak: 'weeks',
    dashboard_monthly_report: 'Monthly Report',
    dashboard_workouts: 'Workouts',
    dashboard_duration: 'Duration',
    dashboard_sets: 'Sets',
    dashboard_muscle_distribution: 'Muscle Distribution',
    dashboard_last_7_days: 'Last 7 days',
    dashboard_last_30_days: 'Last 30 days',
    dashboard_last_90_days: 'Last 90 days',
    dashboard_current: 'Current',
    dashboard_previous: 'Previous',
    dashboard_progression: 'Progression',
    dashboard_search_exercise: 'Search exercise...',
    dashboard_recent: 'Recent',
    dashboard_heaviest: 'Heaviest',
    dashboard_one_rm: '1RM',
    dashboard_best_score: 'Best Score',
    dashboard_average: 'Average',
    dashboard_pace: 'Pace',
    dashboard_last: 'Last',
    dashboard_best: 'Best',
    dashboard_body: 'Body',
    dashboard_body_fat: 'Body Fat',
    dashboard_weight: 'Weight',
    dashboard_to_goal: 'to goal',
    dashboard_log_measurement: 'Log Measurement',
    dashboard_3m: '3M',
    dashboard_6m: '6M',
    dashboard_1y: '1Y',
    dashboard_empty_calendar: 'Complete a workout to see your history here.',
    dashboard_empty_progression: 'Search for an exercise to see your progression.',
    dashboard_exercises: 'exercises',
    dashboard_movements: 'movements',
    dashboard_progressions: 'progressions',
    dashboard_poses: 'poses',
    dashboard_min_cap: 'min cap',
    dashboard_tomorrow: 'Tomorrow',

    // Activity selection (onboarding)
    onboarding_activity_title: 'How do you train?',
    onboarding_activity_subtitle: 'Select all that apply',
    activity_gym: 'Gym',
    activity_crossfit: 'CrossFit',
    activity_calisthenics: 'Calisthenics',
    activity_pilates: 'Pilates',

    // Activity add-ons (onboarding)
    onboarding_addons_title: 'Do you also do any of these?',
    onboarding_addons_skip: 'Skip',
    activity_running: 'Running',
    activity_yoga: 'Yoga',
    frequency_label: 'times/week',

    // Activity time preference (onboarding)
    onboarding_time_title: 'When do you prefer to train?',
    time_morning: 'Morning',
    time_afternoon: 'Afternoon',
    time_evening: 'Evening',
    time_flexible: 'Flexible',

    // Activity card labels
    crossfit_wod: 'WOD',
    crossfit_rounds: 'Rounds',
    crossfit_score: 'Score',
    crossfit_movements: 'Movements',
    calisthenics_level: 'Level',
    calisthenics_hold: 'Hold',
    calisthenics_sets: 'Sets',
    pilates_flow: 'Flow',
    pilates_duration: 'Duration',
    pilates_moves: 'Movements',
    running_distance: 'Distance',
    running_pace: 'Pace',
    running_zone: 'Zone',
    yoga_style: 'Style',
    yoga_duration: 'Duration',
    yoga_focus: 'Focus',

    // Exercise Library
    nav_library: 'Exercises',
    nav_programs: 'Programs',
    library_title: 'Exercise Library',
    library_search_placeholder: 'Search exercises...',
    library_filter_chest: 'Chest',
    library_filter_back: 'Back',
    library_filter_shoulders: 'Shoulders',
    library_filter_arms: 'Arms',
    library_filter_legs: 'Legs',
    library_filter_core: 'Core',
    library_filter_fullbody: 'All',
    library_filter_barbell: 'Barbell',
    library_filter_dumbbell: 'Dumbbell',
    library_filter_cable: 'Cable',
    library_filter_machine: 'Machine',
    library_filter_bodyweight: 'Bodyweight',
    library_filter_band: 'Band',
    library_empty_filter: 'No exercises match these filters. Try removing a filter.',
    library_empty_search: 'No exercises found for',
    library_offline_footer: 'Showing offline library',
    library_staleness: 'Last updated',
    library_staleness_days: 'days ago',
    library_refresh: 'Refresh',
    library_detail_instructions: 'Instructions',
    library_detail_similar: 'Similar exercises',
    library_detail_level: 'Level',
    library_detail_equipment: 'Equipment',
    library_detail_muscles: 'Muscles',

    // Library Filters (redesign)
    library_filters_button: 'Filters',
    library_filters_clear: 'Clear',
    library_filters_clear_all: 'Clear all',
    library_filters_show_results: 'Show results',
    library_filters_muscle_group: 'Muscle Group',
    library_filters_equipment: 'Equipment',
    library_filters_level: 'Level',
    library_filter_beginner: 'Beginner',
    library_filter_intermediate: 'Intermediate',
    library_filter_expert: 'Advanced',

    // Training Page - Plan Selection
    training_empty_title: 'Your training starts here',
    training_empty_desc: 'Choose how to build your training plan',
    training_option_smart: 'Smart Plan',
    training_option_smart_desc: 'Answer a few questions and we build it for you',
    training_option_scratch: 'Build from Scratch',
    training_option_scratch_desc: 'Create your own custom plan',
    training_option_programs: 'Explore Programs',
    training_option_programs_desc: 'Choose from ready-made, tested programs',
    training_active_plan: 'Active Plan',
    training_change_plan: 'Change plan',

    // Programs Page
    programs_title: 'Programs',
    programs_for_you: 'For You',
    programs_all: 'All',
    programs_weeks: 'weeks',
    programs_days_week: 'days/wk',
    programs_start: 'Start Program',
    programs_back: 'Back',
    programs_empty: 'No programs found with these filters.',
    programs_modality_gym: 'Gym',
    programs_modality_crossfit: 'CrossFit',
    programs_modality_calisthenics: 'Calisthenics',
    programs_modality_pilates: 'Pilates',
    programs_modality_running: 'Running',
    programs_modality_yoga: 'Yoga',
    programs_modality_mixed: 'Mixed',
    programs_level_beginner: 'Beginner',
    programs_level_intermediate: 'Intermediate',
    programs_level_advanced: 'Advanced',
    programs_goal_muscle: 'Hypertrophy',
    programs_goal_fat_loss: 'Fat Loss',
    programs_goal_strength: 'Strength',
    programs_goal_endurance: 'Endurance',
    programs_goal_flexibility: 'Flexibility',
    programs_goal_general: 'General',
    programs_duration: 'Duration',
    programs_frequency: 'Frequency',
    programs_level: 'Level',
    programs_goal: 'Goal',
    programs_about: 'About',
    programs_day: 'Day',
    programs_smart_title: 'Smart Trainer',
    programs_smart_desc: 'Answer a few questions and get a personalized plan',

    // Smart Plan Questionnaire
    // Workout Builder
    builder_title: 'Build Workout',
    builder_name_placeholder: 'Workout name (e.g. My Workout A)',
    builder_select_days: 'Days of the week',
    builder_mon: 'Mon',
    builder_tue: 'Tue',
    builder_wed: 'Wed',
    builder_thu: 'Thu',
    builder_fri: 'Fri',
    builder_sat: 'Sat',
    builder_sun: 'Sun',
    builder_empty: 'Tap + to add exercises',
    builder_add_exercise: 'Add exercise',
    builder_sets: 'Sets',
    builder_reps: 'Reps',
    builder_deleted: 'Exercise removed',
    builder_undo: 'Undo',
    builder_days_label: 'days',
    builder_exercises_label: 'exercises',
    builder_save: 'Save Workout',
    builder_pick_exercise: 'Choose Exercise',
    builder_search_placeholder: 'Search exercise...',
    builder_no_results: 'No exercises found',

    smart_plan_title: 'Smart Plan',
    smart_step: 'Step',
    smart_of: 'of',
    smart_next: 'Next',
    smart_finish: 'See my plan',
    smart_q1_title: 'What are your goals?',
    smart_q1_desc: 'Select up to 3 goals',
    smart_q1_muscle: 'Build muscle',
    smart_q1_fat_loss: 'Lose fat',
    smart_q1_strength: 'Get stronger',
    smart_q1_endurance: 'More endurance',
    smart_q1_general: 'General health',
    smart_q2_title: 'What is your experience level?',
    smart_q2_beginner: 'Beginner',
    smart_q2_beginner_desc: 'Less than 1 year training',
    smart_q2_intermediate: 'Intermediate',
    smart_q2_intermediate_desc: '1-3 years training',
    smart_q2_advanced: 'Advanced',
    smart_q2_advanced_desc: 'More than 3 years training',
    smart_q3_title: 'How many days per week?',
    smart_q3_desc: 'We recommend at least 3 days for good results',
    smart_q4_title: 'Where will you train?',
    smart_q4_full_gym: 'Full gym',
    smart_q4_full_gym_desc: 'Barbells, machines, cables, dumbbells',
    smart_q4_home: 'At home',
    smart_q4_home_desc: 'Dumbbells and bodyweight',
    smart_q4_minimal: 'Minimal equipment',
    smart_q4_minimal_desc: 'Bodyweight only',
    smart_q5_title: 'How long per session?',
    smart_q5_30: '30 min',
    smart_q5_45: '45 min',
    smart_q5_60: '60 min',
    smart_q5_90: '90 min',
    smart_result_title: 'Your Plan is Ready!',
    smart_result_desc: 'We created a personalized plan based on your answers.',
    smart_result_goal: 'Goal',
    smart_result_level: 'Level',
    smart_result_days: 'Days/week',
    smart_result_duration: 'Session duration',
    smart_result_equipment: 'Location',
    smart_result_activate: 'Activate Plan',
    smart_result_back: 'Go back and adjust',
    smart_result_exercises: 'Exercises',
    smart_result_priority: 'Priority Muscles',
    smart_result_progression: 'Progression Model',

    // Plan Preview
    smart_preview_title: 'Your Workout Plan',
    smart_preview_hint: 'Tap the swap icon to replace an exercise or X to remove it',
    smart_preview_swap: 'Swap exercise',
    smart_preview_remove: 'Remove exercise',
    smart_preview_empty: 'No exercises for this day',

    // Step 6: Priority Muscles
    smart_q6_title: 'Focus on any specific muscle?',
    smart_q6_desc: 'Select up to 2 muscles to prioritize. Optional — skip for a balanced plan.',
    smart_q6_skip: 'None selected — balanced training for all muscle groups.',

    // Muscle names
    muscle_chest: 'Chest',
    muscle_back: 'Back',
    muscle_shoulders: 'Shoulders',
    muscle_quads: 'Quads',
    muscle_hamstrings: 'Hamstrings',
    muscle_glutes: 'Glutes',
    muscle_biceps: 'Biceps',
    muscle_triceps: 'Triceps',
    muscle_calves: 'Calves',
    muscle_abs: 'Abs',
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem(STORAGE_KEY);
    return saved || 'pt-BR';
  });

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations['pt-BR']?.[key] || key;
  };

  const value = {
    language,
    setLanguage,
    t,
    languages: [
      { code: 'pt-BR', name: 'Português (Brasil)' },
      { code: 'en', name: 'English' }
    ]
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

export default useLanguage;
